name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install
      run: make install
    - name: setup
      run: make setup
    - name: make
      run: make
#   - name: test
#     run: make test

# build-windows:
#   runs-on: windows-latest
#
#   steps:
#   - uses: actions/checkout@v3
#   - name: install
#     run:
#   - name: setup
#     run: make setup
#   - name: make
#     run: make
#   - name: test
#     run: make test
