name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: make install && mkdir build build/shaders
    - name: compile glsl shader files
      run: make compile_shaders
    - name: generate cmake build Makefile
      run: cd build && cmake -S .. -B . -G "Unix Makefiles"
    - name: build
      run: make