name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies (apt)
      run: make install
    - name: Build
      run: |
              mkdir build build/shaders
              make compile_shaders
              cd build && cmake -S .. -B . -G "Unix Makefiles"
              make

  # build-windows:
  #   runs-on: windows-latest
  #   steps:
  #   - uses: actions/checkout@v4
